name:                AOC
version:             0.1.0.0
github:              "java-coding-prodigy/AOC"
#license:             BSD-3-Clause
author:              "java-coding-prodigy"
maintainer:          "java-coding-prodigy@github.com"
copyright:           "2023 java-coding-prodigy"

#extra-source-files:
#- README.md
#- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
#description:         Please see the README on GitHub at <https://github.com/java-coding-prodigy/AOC#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 1.2.4.1
- regex-posix >= 0.96.0.1
- containers >= 0.6.7
- split >= 0.1.2.3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  aoc-exe:
    main:                Day.hs
    source-dirs:         src/main/java/aoc2023
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AOC

tests:
  aoc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AOC
